### ISSUE TITLE
Opinionated template error on internal empty environment variable

### ISSUE THREAD

**Issue by Daniel-Boll** [expressots/expressots#19]
# <h1 align="center"> Opinionated template error on internal empty environment variable </h1>

## Problem

If the user has a internal environment variable that's empty it will not allow the program to load until it has some value

## Environment (PC)

- Kernel: `Linux 6.1.12-artix1-1`
- Shell: `ZSH`
- Package manager: `yarn 1.22.19`
- Expresso version: `1.0.0`

**Comment by jeangondorek** [comment]
Me too, i solved it removing in file ./packages/core/src/console/console.ts (in build of expressots) or ./node_modules/@expressots/core/lib/cjs/console/console.js (in app)

```
let terminalColor: ColorStyle = ColorStyle.None;

        switch (environment.toLowerCase()) {
            case "development":
                terminalColor = ColorStyle.Yellow;
                break;
            case "staging":
                terminalColor = ColorStyle.Blue;
                break;
            case "production":
                terminalColor = ColorStyle.Green;
                break;
            default:
                terminalColor = ColorStyle.Red;
                break;
        }
```

**Comment by rsaz** [comment]
Hi @jeangondorek this is a known error. The detail of this issue is also related to this one here: https://discord.com/channels/370348160398262272/1095412097938104321

The main reason of this problem is that the Environment Validator provider is checking all env variables in Nodejs ecosystem on your Windows or Linux OS, instead of ignoring variables outside of the application context. It should just validate the env variables of your application.

It is in development right now to be released in the next `expressots/core` release.

**Comment by rsaz** [comment]
Hi @Daniel-Boll now the `env-validator-provider` just validates the environment variables created out of the .env file that exist in the nodejs ecossystem. PR reference: #42

Resolution version: `v1.5.1`
